/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ../blender/ComputerV2.glb 
*/

import React from 'react'
import { useGLTF, PerspectiveCamera } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/ComputerV2.glb')
  return (
    <group {...props} dispose={null}>
      <pointLight intensity={54351.413} decay={2} position={[4.076, 5.904, -1.005]} rotation={[-1.839, 0.602, 1.932]} />
      <PerspectiveCamera makeDefault={true} far={100} near={0.1} fov={22.895} position={[7.359, 4.958, 6.926]} rotation={[-0.627, 0.71, 0.441]} />
      <mesh geometry={nodes.ScreenMonitor.geometry} material={materials.Material} position={[0.209, 2.37, 0.072]} scale={[1.343, 1, 0.599]} />
      <mesh geometry={nodes.Base.geometry} material={materials.Material} position={[0.213, 2.48, -0.764]} />
      <mesh geometry={nodes.Cube001.geometry} material={materials.grey} position={[1.224, 0.57, -1.106]} rotation={[-Math.PI / 2, -Math.PI / 2, 0]} />
      <mesh geometry={nodes.Cube002.geometry} material={materials.grey} position={[1.039, 0.57, -1.106]} rotation={[-Math.PI / 2, -Math.PI / 2, 0]} />
      <mesh geometry={nodes.Cube003.geometry} material={materials.grey} position={[-0.721, 0.651, -1.106]} rotation={[-Math.PI / 2, -Math.PI / 2, 0]} scale={[1, 1, 0.554]} />
      <mesh geometry={nodes.Sphere.geometry} material={materials.Green} position={[-0.743, 0.588, -1.123]} scale={[0.022, 0.018, 0.016]} />
      <mesh geometry={nodes.Sphere001.geometry} material={materials.reed} position={[-0.743, 0.529, -1.123]} scale={[0.023, 0.015, 0.016]} />
      <mesh geometry={nodes.Plane.geometry} material={materials.grey} position={[0.188, 2.515, -0.874]} rotation={[-Math.PI / 2, Math.PI / 2, 0]} scale={[1, 1, 1.515]} />
      <mesh geometry={nodes.Base001.geometry} material={materials['Material.002']} position={[0.213, 2.48, -0.764]} />
      <mesh geometry={nodes.Base002.geometry} material={materials['grey mate']} position={[0.213, 2.48, -0.764]} />
      <mesh geometry={nodes.NurbsPath.geometry} material={materials['grey mate']} position={[-3.225, 0, -1.742]} rotation={[-2.077, -0.94, -2.125]} scale={1.239} />
      <mesh geometry={nodes.Cube.geometry} material={materials.Material} position={[-2.114, 0.19, -3.233]} scale={[0.245, 0.172, 0.434]} />
      <mesh geometry={nodes.Sphere002.geometry} material={nodes.Sphere002.material} position={[-2.108, 0.253, -3.122]} scale={[-0.025, -0.091, -0.136]} />
      <mesh geometry={nodes.Cube004.geometry} material={materials['Material.001']} position={[1.258, 0.121, -1.575]} rotation={[-Math.PI, 0, -Math.PI]} scale={[-0.095, -0.043, -0.065]} />
      <mesh geometry={nodes.Cube005.geometry} material={materials['Material.004']} position={[1.251, 0.121, -1.751]} rotation={[-Math.PI, 0, -Math.PI]} scale={[-0.101, -0.043, -0.065]} />
      <mesh geometry={nodes.Cube006.geometry} material={materials['Material.005']} position={[1.213, 0.121, -1.921]} rotation={[-Math.PI, 0, -Math.PI]} scale={[-0.135, -0.043, -0.065]} />
      <mesh geometry={nodes.Cube007.geometry} material={materials['Material.006']} position={[1.282, 0.121, -1.394]} rotation={[-Math.PI, 0, -Math.PI]} scale={[-0.057, -0.043, -0.065]} />
      <mesh geometry={nodes.Cube008.geometry} material={materials['Material.007']} position={[1.142, 0.121, -1.394]} rotation={[-Math.PI, 0, -Math.PI]} scale={[-0.057, -0.043, -0.065]} />
      <mesh geometry={nodes.Cube009.geometry} material={materials['Material.008']} position={[0.858, 0.121, -1.394]} rotation={[-Math.PI, 0, -Math.PI]} scale={[-0.057, -0.043, -0.065]} />
      <mesh geometry={nodes.Cube010.geometry} material={materials['Material.009']} position={[0.998, 0.121, -1.394]} rotation={[-Math.PI, 0, -Math.PI]} scale={[-0.057, -0.043, -0.065]} />
      <mesh geometry={nodes.Cube011.geometry} material={materials['Material.010']} position={[0.422, 0.121, -1.394]} rotation={[-Math.PI, 0, -Math.PI]} scale={[-0.057, -0.043, -0.065]} />
      <mesh geometry={nodes.Cube012.geometry} material={materials['Material.011']} position={[0.281, 0.121, -1.394]} rotation={[-Math.PI, 0, -Math.PI]} scale={[-0.057, -0.043, -0.065]} />
      <mesh geometry={nodes.Cube013.geometry} material={materials['Material.012']} position={[0.565, 0.121, -1.394]} rotation={[-Math.PI, 0, -Math.PI]} scale={[-0.057, -0.043, -0.065]} />
      <mesh geometry={nodes.Cube014.geometry} material={materials['Material.013']} position={[0.706, 0.121, -1.394]} rotation={[-Math.PI, 0, -Math.PI]} scale={[-0.057, -0.043, -0.065]} />
      <mesh geometry={nodes.Cube015.geometry} material={materials['Material.014']} position={[0.127, 0.121, -1.394]} rotation={[-Math.PI, 0, -Math.PI]} scale={[-0.057, -0.043, -0.065]} />
      <mesh geometry={nodes.Cube016.geometry} material={materials['Material.015']} position={[-0.013, 0.121, -1.394]} rotation={[-Math.PI, 0, -Math.PI]} scale={[-0.057, -0.043, -0.065]} />
      <mesh geometry={nodes.Cube017.geometry} material={materials['Material.016']} position={[-0.297, 0.121, -1.394]} rotation={[-Math.PI, 0, -Math.PI]} scale={[-0.057, -0.043, -0.065]} />
      <mesh geometry={nodes.Cube018.geometry} material={materials['Material.017']} position={[-0.157, 0.121, -1.394]} rotation={[-Math.PI, 0, -Math.PI]} scale={[-0.057, -0.043, -0.065]} />
      <mesh geometry={nodes.Cube019.geometry} material={materials['Material.018']} position={[-0.442, 0.121, -1.394]} rotation={[-Math.PI, 0, -Math.PI]} scale={[-0.057, -0.043, -0.065]} />
      <mesh geometry={nodes.Cube020.geometry} material={materials['Material.019']} position={[-0.493, 0.121, -1.583]} rotation={[-Math.PI, 0, -Math.PI]} scale={[-0.057, -0.043, -0.065]} />
      <mesh geometry={nodes.Cube021.geometry} material={materials['Material.020']} position={[-0.212, 0.121, -1.583]} rotation={[-Math.PI, 0, -Math.PI]} scale={[-0.057, -0.043, -0.065]} />
      <mesh geometry={nodes.Cube022.geometry} material={materials['Material.021']} position={[-0.353, 0.121, -1.583]} rotation={[-Math.PI, 0, -Math.PI]} scale={[-0.057, -0.043, -0.065]} />
      <mesh geometry={nodes.Cube023.geometry} material={materials['Material.022']} position={[-0.069, 0.121, -1.583]} rotation={[-Math.PI, 0, -Math.PI]} scale={[-0.057, -0.043, -0.065]} />
      <mesh geometry={nodes.Cube024.geometry} material={materials['Material.023']} position={[0.071, 0.121, -1.583]} rotation={[-Math.PI, 0, -Math.PI]} scale={[-0.057, -0.043, -0.065]} />
      <mesh geometry={nodes.Cube025.geometry} material={materials['Material.024']} position={[0.655, 0.121, -1.583]} rotation={[-Math.PI, 0, -Math.PI]} scale={[-0.057, -0.043, -0.065]} />
      <mesh geometry={nodes.Cube026.geometry} material={materials['Material.025']} position={[0.509, 0.121, -1.583]} rotation={[-Math.PI, 0, -Math.PI]} scale={[-0.057, -0.043, -0.065]} />
      <mesh geometry={nodes.Cube027.geometry} material={materials['Material.026']} position={[0.225, 0.121, -1.583]} rotation={[-Math.PI, 0, -Math.PI]} scale={[-0.057, -0.043, -0.065]} />
      <mesh geometry={nodes.Cube028.geometry} material={materials['Material.027']} position={[0.366, 0.121, -1.583]} rotation={[-Math.PI, 0, -Math.PI]} scale={[-0.057, -0.043, -0.065]} />
      <mesh geometry={nodes.Cube029.geometry} material={materials['Material.028']} position={[0.943, 0.121, -1.583]} rotation={[-Math.PI, 0, -Math.PI]} scale={[-0.057, -0.043, -0.065]} />
      <mesh geometry={nodes.Cube030.geometry} material={materials['Material.029']} position={[0.802, 0.121, -1.583]} rotation={[-Math.PI, 0, -Math.PI]} scale={[-0.057, -0.043, -0.065]} />
      <mesh geometry={nodes.Cube031.geometry} material={materials['Material.030']} position={[1.086, 0.121, -1.583]} rotation={[-Math.PI, 0, -Math.PI]} scale={[-0.057, -0.043, -0.065]} />
      <mesh geometry={nodes.Cube032.geometry} material={materials['Material.031']} position={[1.04, 0.121, -1.743]} rotation={[-Math.PI, 0, -Math.PI]} scale={[-0.057, -0.043, -0.065]} />
      <mesh geometry={nodes.Cube033.geometry} material={materials['Material.032']} position={[0.756, 0.121, -1.743]} rotation={[-Math.PI, 0, -Math.PI]} scale={[-0.057, -0.043, -0.065]} />
      <mesh geometry={nodes.Cube034.geometry} material={materials['Material.033']} position={[0.897, 0.121, -1.743]} rotation={[-Math.PI, 0, -Math.PI]} scale={[-0.057, -0.043, -0.065]} />
      <mesh geometry={nodes.Cube035.geometry} material={materials['Material.034']} position={[0.32, 0.121, -1.743]} rotation={[-Math.PI, 0, -Math.PI]} scale={[-0.057, -0.043, -0.065]} />
      <mesh geometry={nodes.Cube036.geometry} material={materials['Material.035']} position={[0.18, 0.121, -1.743]} rotation={[-Math.PI, 0, -Math.PI]} scale={[-0.057, -0.043, -0.065]} />
      <mesh geometry={nodes.Cube037.geometry} material={materials['Material.036']} position={[0.463, 0.121, -1.743]} rotation={[-Math.PI, 0, -Math.PI]} scale={[-0.057, -0.043, -0.065]} />
      <mesh geometry={nodes.Cube038.geometry} material={materials['Material.037']} position={[0.609, 0.121, -1.743]} rotation={[-Math.PI, 0, -Math.PI]} scale={[-0.057, -0.043, -0.065]} />
      <mesh geometry={nodes.Cube039.geometry} material={materials['Material.038']} position={[0.025, 0.121, -1.743]} rotation={[-Math.PI, 0, -Math.PI]} scale={[-0.057, -0.043, -0.065]} />
      <mesh geometry={nodes.Cube040.geometry} material={materials['Material.039']} position={[-0.115, 0.121, -1.743]} rotation={[-Math.PI, 0, -Math.PI]} scale={[-0.057, -0.043, -0.065]} />
      <mesh geometry={nodes.Cube041.geometry} material={materials['Material.040']} position={[-0.399, 0.121, -1.743]} rotation={[-Math.PI, 0, -Math.PI]} scale={[-0.057, -0.043, -0.065]} />
      <mesh geometry={nodes.Cube042.geometry} material={materials['Material.041']} position={[-0.258, 0.121, -1.743]} rotation={[-Math.PI, 0, -Math.PI]} scale={[-0.057, -0.043, -0.065]} />
      <mesh geometry={nodes.Cube043.geometry} material={materials['Material.042']} position={[-0.304, 0.121, -1.923]} rotation={[-Math.PI, 0, -Math.PI]} scale={[-0.057, -0.043, -0.065]} />
      <mesh geometry={nodes.Cube044.geometry} material={materials['Material.043']} position={[-0.16, 0.121, -1.923]} rotation={[-Math.PI, 0, -Math.PI]} scale={[-0.057, -0.043, -0.065]} />
      <mesh geometry={nodes.Cube045.geometry} material={materials['Material.044']} position={[-0.02, 0.121, -1.923]} rotation={[-Math.PI, 0, -Math.PI]} scale={[-0.057, -0.043, -0.065]} />
      <mesh geometry={nodes.Cube046.geometry} material={materials['Material.045']} position={[0.559, 0.121, -1.923]} rotation={[-Math.PI, 0, -Math.PI]} scale={[-0.057, -0.043, -0.065]} />
      <mesh geometry={nodes.Cube047.geometry} material={materials['Material.046']} position={[0.418, 0.121, -1.923]} rotation={[-Math.PI, 0, -Math.PI]} scale={[-0.057, -0.043, -0.065]} />
      <mesh geometry={nodes.Cube048.geometry} material={materials['Material.047']} position={[0.134, 0.121, -1.923]} rotation={[-Math.PI, 0, -Math.PI]} scale={[-0.057, -0.043, -0.065]} />
      <mesh geometry={nodes.Cube049.geometry} material={materials['Material.048']} position={[0.275, 0.121, -1.923]} rotation={[-Math.PI, 0, -Math.PI]} scale={[-0.057, -0.043, -0.065]} />
      <mesh geometry={nodes.Cube050.geometry} material={materials['Material.049']} position={[0.851, 0.121, -1.923]} rotation={[-Math.PI, 0, -Math.PI]} scale={[-0.057, -0.043, -0.065]} />
      <mesh geometry={nodes.Cube051.geometry} material={materials['Material.050']} position={[0.711, 0.121, -1.923]} rotation={[-Math.PI, 0, -Math.PI]} scale={[-0.057, -0.043, -0.065]} />
      <mesh geometry={nodes.Cube052.geometry} material={materials['Material.051']} position={[0.995, 0.121, -1.923]} rotation={[-Math.PI, 0, -Math.PI]} scale={[-0.057, -0.043, -0.065]} />
      <mesh geometry={nodes.Cube053.geometry} material={materials['Material.052']} position={[1.291, 0.121, -2.091]} rotation={[-Math.PI, 0, -Math.PI]} scale={[-0.057, -0.043, -0.065]} />
      <mesh geometry={nodes.Cube054.geometry} material={materials['Material.053']} position={[1.007, 0.121, -2.091]} rotation={[-Math.PI, 0, -Math.PI]} scale={[-0.057, -0.043, -0.065]} />
      <mesh geometry={nodes.Cube055.geometry} material={materials['Material.054']} position={[1.147, 0.121, -2.091]} rotation={[-Math.PI, 0, -Math.PI]} scale={[-0.057, -0.043, -0.065]} />
      <mesh geometry={nodes.Cube056.geometry} material={materials['Material.055']} position={[0.513, 0.121, -2.089]} rotation={[-Math.PI, 0, -Math.PI]} scale={[-0.403, -0.043, -0.065]} />
      <mesh geometry={nodes.Cube057.geometry} material={materials['Material.056']} position={[-0.143, 0.121, -2.09]} rotation={[-Math.PI, 0, -Math.PI]} scale={[-0.057, -0.043, -0.065]} />
      <mesh geometry={nodes.Cube058.geometry} material={materials['Material.057']} position={[-0.284, 0.121, -2.09]} rotation={[-Math.PI, 0, -Math.PI]} scale={[-0.057, -0.043, -0.065]} />
      <mesh geometry={nodes.Cube059.geometry} material={materials['Material.058']} position={[0, 0.121, -2.09]} rotation={[-Math.PI, 0, -Math.PI]} scale={[-0.057, -0.043, -0.065]} />
      <mesh geometry={nodes.Cube060.geometry} material={materials['Material.059']} position={[-0.567, 0.121, -2.09]} rotation={[-Math.PI, 0, -Math.PI]} scale={[-0.057, -0.043, -0.065]} />
      <mesh geometry={nodes.Cube061.geometry} material={materials['Material.060']} position={[-0.708, 0.121, -2.09]} rotation={[-Math.PI, 0, -Math.PI]} scale={[-0.057, -0.043, -0.065]} />
      <mesh geometry={nodes.Cube062.geometry} material={materials['Material.061']} position={[-0.851, 0.121, -2.09]} rotation={[-Math.PI, 0, -Math.PI]} scale={[-0.057, -0.043, -0.065]} />
      <mesh geometry={nodes.Cube063.geometry} material={materials['Material.062']} position={[-0.652, 0.121, -1.382]} rotation={[-Math.PI, 0, -Math.PI]} scale={[-0.115, -0.043, -0.065]} />
      <mesh geometry={nodes.Cube064.geometry} material={materials['Material.063']} position={[-0.672, 0.121, -1.575]} rotation={[-Math.PI, 0, -Math.PI]} scale={[-0.095, -0.043, -0.065]} />
      <mesh geometry={nodes.Cube065.geometry} material={materials['Material.064']} position={[-0.629, 0.121, -1.742]} rotation={[-Math.PI, 0, -Math.PI]} scale={[-0.135, -0.043, -0.065]} />
      <mesh geometry={nodes.Cube066.geometry} material={materials['Material.065']} position={[-0.506, 0.121, -1.919]} rotation={[-Math.PI, 0, -Math.PI]} scale={[-0.12, -0.043, -0.065]} />
      <mesh geometry={nodes.Cube067.geometry} material={materials['Material.066']} position={[-0.708, 0.121, -1.904]} rotation={[-Math.PI, 0, -Math.PI]} scale={[-0.057, -0.043, -0.065]} />
      <mesh geometry={nodes.Cube068.geometry} material={materials['Material.067']} position={[-0.42, 0.121, -2.09]} rotation={[-Math.PI, 0, -Math.PI]} scale={[-0.057, -0.043, -0.065]} />
    </group>
  )
}

useGLTF.preload('/ComputerV2.glb')
