/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ../public/LittleMonster1.glb 
*/

import React from 'react'
import { useGLTF, PerspectiveCamera, useAnimations } from '@react-three/drei'

export function LittleMonsterModel(props) {
  const group = React.useRef()
  const { nodes, materials, animations } = useGLTF('/LittleMonster1.glb')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <pointLight name="Light" intensity={2} decay={2} position={[2.241, 4.392, 5.72]} rotation={[-1.839, 0.602, 1.932]} scale={0.3} />
        <PerspectiveCamera name="Camera" makeDefault={true} far={100} near={0.1} fov={22.895} position={[1.5, 12.225, 23.237]} rotation={[-0.387, 0.108, 0.054]} scale={[6.328, 2.807, 5.368]} />
        <mesh name="SurfSphere" geometry={nodes.SurfSphere.geometry} material={materials.Material} position={[-0.302, 3.62, -0.558]} rotation={[0, 0.33, 0]} scale={[3.069, 3.311, 3.014]} />
        <mesh name="SurfSphere001" geometry={nodes.SurfSphere001.geometry} material={materials.Material} position={[-2.443, 2.962, 0.514]} rotation={[0.851, 1.021, -0.658]} scale={[1.3, 1.354, 1.942]} />
        <mesh name="SurfSphere002" geometry={nodes.SurfSphere002.geometry} material={materials.Material} position={[2.251, 2.884, -1.139]} rotation={[Math.PI, -0.33, 0]} scale={[-0.958, -1.354, -1.942]} />
        <mesh name="SurfSphere003" geometry={nodes.SurfSphere003.geometry} material={materials.Material} position={[-1.892, 0.556, -0.012]} rotation={[0, 0.33, 0]} scale={[0.64, 0.764, 0.659]} />
        <mesh name="SurfSphere004" geometry={nodes.SurfSphere004.geometry} material={materials.Material} position={[1.172, 0.579, -1.064]} rotation={[Math.PI, -0.337, Math.PI]} scale={[0.64, 0.764, 0.659]} />
        <mesh name="SurfSphere005" geometry={nodes.SurfSphere005.geometry} material={materials['Material.001']} position={[1.2, 6.106, -1.116]} rotation={[0, 0.33, -0.496]} scale={[0.647, 0.77, 0.667]} />
        <mesh name="SurfSphere006" geometry={nodes.SurfSphere006.geometry} material={materials['Material.001']} position={[-1.781, 6.151, -0.094]} rotation={[0, 0.33, 0.28]} scale={[0.647, 0.77, 0.667]} />
        <mesh name="NurbsPath" geometry={nodes.NurbsPath.geometry} material={materials['Material.002']} position={[-0.552, 4.962, 1.981]} rotation={[0, -0.065, 0]} scale={[0.186, 1.255, 1.619]} />
        <mesh name="NurbsPath001" geometry={nodes.NurbsPath001.geometry} material={materials['Material.003']} position={[1.235, 4.98, 1.36]} rotation={[0, 0.657, 0]} scale={[0.187, 1.403, 1.61]} />
        <mesh name="Cylinder" geometry={nodes.Cylinder.geometry} material={materials['Material.001']} position={[-1.012, 4.548, 1.944]} rotation={[1.441, -0.03, 0.227]} scale={[0.235, 0.024, 0.118]} />
        <mesh name="Cylinder001" geometry={nodes.Cylinder001.geometry} material={materials['Material.004']} position={[1.655, 4.548, 1.128]} rotation={[1.482, 0.099, -0.835]} scale={[0.235, 0.024, 0.118]} />
        <mesh name="NurbsPath002" geometry={nodes.NurbsPath002.geometry} material={materials['Material.005']} position={[0.412, 4.609, 1.936]} rotation={[0, 0.174, 0]} scale={[0.103, 0.667, 1.619]} />
      </group>
    </group>
  )
}

useGLTF.preload('/LittleMonster1.glb')

// Componente principal para usar en Projects.jsx
const LittleMonster1 = (props) => <LittleMonsterModel {...props} />;
export default LittleMonster1;
